FROM python:3.7

WORKDIR /block-producer-calculator-back
COPY . /block-producer-calculator-back

RUN pip3 install -r /block-producer-calculator-back/requirements.txt

CMD gunicorn -w 2 --bind 0.0.0.0:$PORT calculator.server:server
